/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.hangman;

public class App {

    public static void main(String[] args) {
        GetWord getWord = new GetWord();
        PlayGame playGame = new PlayGame(getWord.getGuessedWord());
    }
}

/**
 *  _____    
 * |    |    
 * |   ( )   
 * |   /|\   
 * |   / \   
 * |_________
 */
